apiVersion: v1
kind: PersistentVolume
metadata:
  name: %SERVICE_NAME%-azurefile-pv
spec:
  capacity:
    storage: %STORAGE_SIZE%
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-static
  csi:
    driver: file.csi.azure.com
    volumeHandle: %AZURE_GROUP_STORAGE%#%STORAGE_ACCOUNT_NAME%#%STORAGE_SHARE_NAME%
    volumeAttributes:
      shareName: %STORAGE_SHARE_NAME%
      storageAccount: %STORAGE_ACCOUNT_NAME%
      resourceGroup: %AZURE_GROUP_STORAGE%
      clientID: %IDENTITY_CLIENT_ID%
      mountWithWorkloadIdentityToken: "true"
