apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %SERVICE_NAME%-azurefile-pvc
  namespace: %KUBERNETES_NAMESPACE%
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-static
  resources:
    requests:
      storage: %STORAGE_SIZE%